-- CALI Prospect Compass — contatos de hoje (20)
-- Enriquecimento operacional para formar estoque A/B utilizável em 01/09/2026.
-- Atualiza apenas os IDs listados e preserva os demais campos.

UPDATE public.leads SET icp_fit=9,status='Qualificado',prioridade='Alta',nome_decisor='Flavio Fernando Fachi',cargo_decisor='Sócio-administrador',tamanho_time='51-200 funcionários',sinal_compra='Sem sinal forte',angulo_abordagem='Operação industrial de automação com múltiplas frentes técnicas. Abrir com Flavio para confirmar quem toca gestão de pessoas e liderança, sem presumir dor.',proximo_passo='Abordar Flavio pelo canal disponível e validar responsável por People.',linkedin_decisor='https://br.linkedin.com/in/flavio-fernando-fachi-a742a428',atualizado_em=now() WHERE id='f561bf54-14e0-42ca-916a-aeb5c843d1d2';
UPDATE public.leads SET icp_fit=9,status='Qualificado',prioridade='Alta',nome_decisor='Marco Antonio Caparroz de Medeiros',cargo_decisor='Sócio-administrador',tamanho_time='30-49 funcionários',sinal_compra='Sem sinal forte',angulo_abordagem='Clínica com estrutura relevante e vários especialistas. Abrir com um dos sócios para entender quem responde por gestão de pessoas e operação.',proximo_passo='Abordar Marco Antonio e confirmar responsável por People.',atualizado_em=now() WHERE id='2473474e-fbcc-458b-83e0-543a8877a812';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Alta',nome_decisor='Antonio Adelson Tamanini',cargo_decisor='Sócio-administrador',tamanho_time='11-50 funcionários',sinal_compra='Sem sinal forte',angulo_abordagem='Indústria de automação em Curitiba com operação técnica consolidada. Conversa neutra sobre quem sustenta a frente de pessoas e liderança.',proximo_passo='Abordar Antonio Adelson e validar quem toca gestão de pessoas.',atualizado_em=now() WHERE id='9dcf51b4-1306-4a83-b212-4e62c8823295';
UPDATE public.leads SET icp_fit=9,status='Qualificado',prioridade='Alta',nome_decisor='Taynara Marques Wiegand',cargo_decisor='Sócia-administradora',tamanho_time='11-50 funcionários',sinal_compra='Sem sinal forte',angulo_abordagem='Indústria de máquinas, usinagem e automação com equipe técnica. Abrir com Taynara para confirmar a frente de gestão de pessoas.',proximo_passo='Abordar Taynara pelo telefone corporativo e buscar canal direto/LinkedIn.',atualizado_em=now() WHERE id='734a0bc4-9616-4aea-a505-7cb681954b86';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Média',nome_decisor='Luiz Alberto Lopes',cargo_decisor='Sócio-administrador',sinal_compra='Sem sinal forte',angulo_abordagem='Indústria de máquinas para alimentos ativa desde 1996. Abordar o sócio com pergunta de roteamento sobre gestão de pessoas.',proximo_passo='Abordar Luiz e confirmar se a frente fica com ele ou outro responsável.',atualizado_em=now() WHERE id='1fdb4492-6555-426b-b0a5-5af4d970627f';
UPDATE public.leads SET icp_fit=9,status='Qualificado',prioridade='Alta',nome_decisor='Carlos Benecke',cargo_decisor='Sócio-administrador',tamanho_time='51-200 funcionários',sinal_compra='Sem sinal forte',angulo_abordagem='Indústria mecânica automotiva com estrutura e operação de maior complexidade. Abrir com Carlos para entender governança de pessoas e liderança.',proximo_passo='Abordar Carlos e validar responsável por People/RH.',atualizado_em=now() WHERE id='765ab180-cce9-4a36-8737-7f3c4f73e2d2';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Média',nome_decisor='Augusto Cesar Porfirio Guilherme',cargo_decisor='Sócio-administrador',sinal_compra='Sem sinal forte',angulo_abordagem='Fábrica de alimentos em Curitiba, com produção e operação de equipe. Abrir pelo contexto operacional e perguntar quem toca pessoas.',proximo_passo='Abordar Augusto e confirmar responsável pela gestão de pessoas.',atualizado_em=now() WHERE id='322b5a45-fcf6-4888-96da-715d160e6911';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Média',nome_decisor='Augustinho Sebastiao Oszika',cargo_decisor='Sócio-administrador',sinal_compra='Sem sinal forte',angulo_abordagem='Indústria de embalagens ativa desde 2000. Abordar o sócio para identificar quem responde por gestão de pessoas e liderança.',proximo_passo='Abordar Augustinho e validar canal/responsável por People.',atualizado_em=now() WHERE id='355a6967-db8b-4b91-a44c-0c4983d3e1c3';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Alta',nome_decisor='Janaina Machado',cargo_decisor='Sócia-administradora',sinal_compra='Sem sinal forte',angulo_abordagem='Indústria com matriz e filiais em diferentes estados. Abrir com Janaina sobre quem centraliza gestão de pessoas e liderança.',proximo_passo='Abordar Janaina e confirmar responsável pela frente de People.',atualizado_em=now() WHERE id='7f8d0a22-77fb-4e33-9078-57ca90df25de';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Média',nome_decisor='Jose Denilson Nichele',cargo_decisor='Sócio-administrador',sinal_compra='Sem sinal forte',angulo_abordagem='Indústria cerâmica tradicional em Curitiba. Abordar o sócio com conversa direta sobre quem toca a gestão de pessoas.',proximo_passo='Abordar Jose Denilson e validar responsável por People.',atualizado_em=now() WHERE id='62f9b811-1a4d-4091-9386-ace90ca7b2a4';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Média',nome_decisor='Maria Jose Clazer de Andrade',cargo_decisor='Sócia-administradora',sinal_compra='Sem sinal forte',angulo_abordagem='Indústria de plásticos e borrachas ativa desde 1996. Abrir com a administradora para entender quem cuida da frente de pessoas.',proximo_passo='Abordar Maria Jose e validar responsável por gestão de pessoas.',atualizado_em=now() WHERE id='3871a105-359f-421b-9f23-01b72c6b1a09';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Média',nome_decisor='Maira Ribeiro Baptista',cargo_decisor='Sócia-administradora',sinal_compra='Sem sinal forte',angulo_abordagem='Fábrica de cerâmica com operação industrial. Abordar Maira para confirmar a responsabilidade por pessoas e liderança.',proximo_passo='Abordar Maira e validar responsável por People.',atualizado_em=now() WHERE id='7564fd99-b16e-4fc5-a42b-af1661c71570';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Média',nome_decisor='Leonardo Baptista Frank',cargo_decisor='Sócio-administrador',sinal_compra='Sem sinal forte',angulo_abordagem='Clínica médica com filial em Curitiba e operação multidisciplinar. Abrir com Leonardo para identificar quem toca pessoas e operação.',proximo_passo='Abordar Leonardo e confirmar responsável pela gestão de pessoas.',atualizado_em=now() WHERE id='6f9722c5-904f-4a15-9b21-26b52155ae6a';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Alta',nome_decisor='Flavio Fernando Fachi',cargo_decisor='Sócio-administrador',sinal_compra='Sem sinal forte',angulo_abordagem='Indústria de automação com matriz em Curitiba e filial em Joinville. Abordar Flavio com foco em quem sustenta gestão de pessoas e liderança.',proximo_passo='Abordar Flavio e validar responsável por People.',atualizado_em=now() WHERE id='b0bea3eb-f5e2-4e5d-8d1a-f984c75640a9';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Média',nome_decisor='Juliana Tabarelli Brondani',cargo_decisor='Sócia-administradora',tamanho_time='11-50 funcionários',sinal_compra='Sem sinal forte',angulo_abordagem='Clínica Top Saúde Hauer com estrutura de atendimento e equipe compatível. Abrir com Juliana para confirmar quem toca gestão de pessoas.',proximo_passo='Abordar Juliana e validar responsável pela frente de People.',atualizado_em=now() WHERE id='3e817f60-d37f-4004-a902-807456cdea10';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Média',nome_decisor='Natan de Paula Ribas Gemin',cargo_decisor='Sócio-administrador',sinal_compra='Sem sinal forte',angulo_abordagem='Empresa de embalagens com operação própria. Retomar com Natan/Luciana conforme resposta e entender o escopo real que já fica com a liderança.',proximo_passo='Continuar conversa a partir da resposta recebida e qualificar necessidade.',atualizado_em=now() WHERE id='2401fcfd-72fd-4091-b93d-1b6569123da6';
UPDATE public.leads SET icp_fit=7,status='Qualificado',prioridade='Média',nome_decisor='Leandro Gomes Iwersen',cargo_decisor='Sócio-administrador',sinal_compra='Sem sinal forte',angulo_abordagem='Imobiliária local com decisor identificado. Abrir com pergunta curta para entender quem toca gestão de pessoas.',proximo_passo='Abordar Leandro e validar responsável por People.',atualizado_em=now() WHERE id='c4bb21c6-3288-4ae0-af6b-795669c4aa33';
UPDATE public.leads SET icp_fit=9,status='Sinal identificado',prioridade='Alta',nome_decisor='Luis César Araújo',cargo_decisor='CEO e cofundador',tamanho_time='11-50 funcionários',angulo_abordagem='Contratação ativa em empresa de 11-50 pessoas. Abordar Luis com contexto de crescimento do time e organização da gestão de pessoas, sem assumir problema.',proximo_passo='Abordar Luis com referência à contratação recente e perguntar quem toca People.',atualizado_em=now() WHERE id='6ce7706e-18bc-4e35-8a87-dd061227c55e';
UPDATE public.leads SET icp_fit=9,status='Qualificado',prioridade='Alta',nome_decisor='Jose Carlos Zanlorenzi Neto',cargo_decisor='Administrador',sinal_compra='Sem sinal forte',angulo_abordagem='Rede de mercados com múltiplas unidades em Curitiba, incluindo novas filiais em 2026. Abordar Jose Carlos sobre quem centraliza gestão de pessoas e liderança.',proximo_passo='Abordar Jose Carlos e validar responsável por People.',atualizado_em=now() WHERE id='4c2a53a4-a93d-443d-ab8c-82bd4d63d202';
UPDATE public.leads SET icp_fit=8,status='Qualificado',prioridade='Média',nome_decisor='Renan Andre Abdalla de Souza',cargo_decisor='Sócio-administrador',sinal_compra='Sem sinal forte',angulo_abordagem='Clínica de saúde integrativa com mais de um endereço e decisor identificado. Abrir com Renan para entender quem toca gestão de pessoas e operação.',proximo_passo='Abordar Renan e confirmar responsável por gestão de pessoas.',atualizado_em=now() WHERE id='2d887443-370c-4521-a398-ab0f43f89cc0';
